### ISSUE TITLE
Should EUNN cite 2008 work based on SU(3) learning representation by Simone Fiori?

### ISSUE THREAD

**Issue by JordanMicahBennett** [jingli9111/EUNN-tensorflow#3]
EUNN is non-trivially similar to earlier work regarding SU(3) learning representation.

Perhaps a revision of EUNN should include a citation  to the work below:

Reference: [A study on neural learning on manifold foliations: the case of the Lie group SU(3)](https://www.ncbi.nlm.nih.gov/pubmed/18085982)

**Comment by jingli9111** [comment]
The architecture is truly similar. Thanks for pointing it out. We will add such citation in the future revision.
